apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  namespace: app-web
  labels:
    app: guestbook-ui
spec:
  type: NodePort
  selector:
    app: guestbook-ui
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080